name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Maintenance'
    labels:
      - 'maintenance'
      - 'infrastructure'
      - 'automation'
      - 'documentation'
      - 'dependencies'
  - title: 'Performance'
    label: 'performance'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'maintenance'
      - 'infrastructure'
      - 'automation'
      - 'documentation'
      - 'dependencies'
  default: 'patch'

exclude-labels:
  - 'skip-changelog'
