name: Test

on:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1.16.0
      with:
        otp-version: '26.0'
        elixir-version: '1.15.7'

    - name: Restore dependencies cache
      uses: actions/cache@v3
      env:
        cache-name: deps-v1
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-${{ env.cache-name }}-

    - name: Restore build cache
      uses: actions/cache@v3
      env:
        cache-name: build-v1
      with:
        path: _build
        key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-${{ env.cache-name }}-
          ${{ runner.os }}-mix-

    # Force a full recompile only on builds that are retried.
    - name: Force a full recompile
      if: github.run_attempt != '1'
      run: |
        mix deps.clean --all
        mix clean
      shell: sh

    - name: Install dependencies
      run: mix deps.get

    - name: Compiles without warnings
      run: mix compile --warnings-as-errors

    - name: Run tests
      run: mix test --warnings-as-errors --cover --export-coverage default

    - name: Run test coverage
      run: mix test.coverage

    - name: Check Formatting
      run: mix format --check-formatted

    - name: Check Unused Dependencies
      run: mix format --check-formatted

